---
php:
    brew:
        taps:
            - homebrew/dupes
            - homebrew/versions
            - homebrew/php
        packages:
            - php55
            - php55-mcrypt
            - php-code-sniffer
            - composer
            - phpmd
            - phpunit
